[options]
addons_path = /mnt/custom-addons
data_dir = /var/lib/odoo
db_host = db
db_user = odoo
db_password = odoo
admin_passwd = ef04ffbb266a8aae37ade30e44337405d4e3754c
limit_memory_hard = 4684354560
limit_memory_soft = 4147483648
limit_time_real = 900

